UPDATE learning_units
SET title='短 /ɪ/ 与长 /iː/',
    content_json='{"category":"短元音与长元音","title":"/ɪ/ 和 /iː/","description":"两者都是前元音，主要区别是声音长度、紧张度和嘴角展开程度。","phonemes":[{"phonemeId":"p_1","ipa":"/ɪ/","description":"短促放松，舌位稍低，嘴角自然。","mouth":{"type":"relaxed"},"audioUrl":null,"examples":["sit","ship","bit"]},{"phonemeId":"p_2","ipa":"/iː/","description":"更长更紧，舌位更高，嘴角略向两侧展开。","mouth":{"type":"smile"},"audioUrl":null,"examples":["seat","sheep","beat"]}],"audioPairs":[{"left":"sit","right":"seat","tip":"先听元音长度：sit 短，seat 长。"},{"left":"ship","right":"sheep","tip":"ship 嘴角放松，sheep 嘴角更展开。"}],"memoryTip":"先判断有没有拉长，再看嘴角是否展开。"}'
WHERE id='unit_compare_1';

INSERT INTO learning_units (id, template_code, content_type, title, content_json, sort_order, enabled) VALUES
('unit_compare_02', 'phoneme-compare', 'PHONEME_COMPARE', '短 /e/ 与开 /æ/', '{"category":"短元音对比","title":"/e/ 和 /æ/","description":"/e/ 开口中等，/æ/ 开口更大，下颌更低。","phonemes":[{"phonemeId":"p_v_03","ipa":"/e/","description":"舌前部中等抬起，声音短而清楚。","mouth":{"type":"relaxed"},"audioUrl":null,"examples":["bed","pen","head"]},{"phonemeId":"p_v_04","ipa":"/æ/","description":"舌位更低，下颌明显打开。","mouth":{"type":"open"},"audioUrl":null,"examples":["bad","pan","had"]}],"audioPairs":[{"left":"bed","right":"bad","tip":"bad 的开口比 bed 大。"},{"left":"pen","right":"pan","tip":"听中间元音：/e/ 更收，/æ/ 更开。"}],"memoryTip":"读 /æ/ 先把嘴打开，/e/ 不要打开到那么大。"}', 2, TRUE),
('unit_compare_03', 'phoneme-compare', 'PHONEME_COMPARE', '短 /ʊ/ 与长 /uː/', '{"category":"短元音与长元音","title":"/ʊ/ 和 /uː/","description":"两者都偏后且圆唇，/ʊ/ 短而松，/uː/ 长而紧。","phonemes":[{"phonemeId":"p_v_09","ipa":"/ʊ/","description":"短促，圆唇较轻，舌后部不太紧。","mouth":{"type":"closed"},"audioUrl":null,"examples":["full","pull","look"]},{"phonemeId":"p_v_08","ipa":"/uː/","description":"长音，双唇更圆，声音保持稳定。","mouth":{"type":"closed"},"audioUrl":null,"examples":["fool","pool","Luke"]}],"audioPairs":[{"left":"full","right":"fool","tip":"full 短而松，fool 长而圆。"},{"left":"pull","right":"pool","tip":"先听长度，再听圆唇紧张度。"}],"memoryTip":"/uː/ 有长音符号，声音要稳稳拉住。"}', 3, TRUE),
('unit_compare_04', 'phoneme-compare', 'PHONEME_COMPARE', '短 /ɒ/ 与长 /ɔː/', '{"category":"短元音与长元音","title":"/ɒ/ 和 /ɔː/","description":"英式发音中 /ɒ/ 短促，/ɔː/ 更长，圆唇感更稳定。","phonemes":[{"phonemeId":"p_v_11","ipa":"/ɒ/","description":"开口较大，声音短促。","mouth":{"type":"open"},"audioUrl":null,"examples":["cot","hot","stock"]},{"phonemeId":"p_v_10","ipa":"/ɔː/","description":"后元音拉长，双唇略圆。","mouth":{"type":"open"},"audioUrl":null,"examples":["caught","short","stork"]}],"audioPairs":[{"left":"cot","right":"caught","tip":"英式 caught 的元音更长。"},{"left":"stock","right":"stork","tip":"stork 中间是长 /ɔː/，不要读短。"}],"memoryTip":"看到 /ː/ 先提醒自己不要收得太快。"}', 4, TRUE),
('unit_compare_05', 'phoneme-compare', 'PHONEME_COMPARE', '短 /ʌ/ 与长 /ɑː/', '{"category":"短元音与长元音","title":"/ʌ/ 和 /ɑː/","description":"/ʌ/ 短而居中，/ɑː/ 更靠后且拉长。","phonemes":[{"phonemeId":"p_v_07","ipa":"/ʌ/","description":"短促，中后位置，嘴唇不圆。","mouth":{"type":"open"},"audioUrl":null,"examples":["cut","luck","hut"]},{"phonemeId":"p_v_12","ipa":"/ɑː/","description":"开口较大，舌身后缩，声音拉长。","mouth":{"type":"open"},"audioUrl":null,"examples":["cart","lark","heart"]}],"audioPairs":[{"left":"cut","right":"cart","tip":"cart 的元音明显更长更靠后。"},{"left":"hut","right":"heart","tip":"听长度和舌位后移。"}],"memoryTip":"/ʌ/ 像 cup 的短音，/ɑː/ 像 car 的长音。"}', 5, TRUE),
('unit_compare_06', 'phoneme-compare', 'PHONEME_COMPARE', '弱 /ə/ 与长 /ɜː/', '{"category":"中央元音对比","title":"/ə/ 和 /ɜː/","description":"/ə/ 常在非重读音节里轻轻带过，/ɜː/ 是重读长元音。","phonemes":[{"phonemeId":"p_v_06","ipa":"/ə/","description":"轻、短、放松，常在弱读音节。","mouth":{"type":"relaxed"},"audioUrl":null,"examples":["about","teacher","banana"]},{"phonemeId":"p_v_05","ipa":"/ɜː/","description":"声音更饱满，保持长度，英式通常不卷舌。","mouth":{"type":"relaxed"},"audioUrl":null,"examples":["bird","word","first"]}],"audioPairs":[{"left":"sofa","right":"surfer","tip":"sofa 末尾是轻 /ə/，surfer 重读部分更长。"},{"left":"about","right":"a bird","tip":"/ə/ 弱，/ɜː/ 稳定拉长。"}],"memoryTip":"轻轻带过的是 /ə/，重读且拉长的是 /ɜː/。"}', 6, TRUE),
('unit_compare_07', 'phoneme-compare', 'PHONEME_COMPARE', '双元音 /eɪ/ 与 /aɪ/', '{"category":"双元音对比","title":"/eɪ/ 和 /aɪ/","description":"两者结尾都向 /ɪ/ 收，起点不同：/eɪ/ 更靠前中，/aɪ/ 开口更大。","phonemes":[{"phonemeId":"p_v_13","ipa":"/eɪ/","description":"从 /e/ 附近开始，轻轻滑向 /ɪ/。","mouth":{"type":"relaxed"},"audioUrl":null,"examples":["late","day","say"]},{"phonemeId":"p_v_14","ipa":"/aɪ/","description":"从更开的 /a/ 起步，再向 /ɪ/ 收。","mouth":{"type":"open"},"audioUrl":null,"examples":["light","my","sigh"]}],"audioPairs":[{"left":"late","right":"light","tip":"light 起点开口更大。"},{"left":"day","right":"die","tip":"day 从 /e/ 起，die 从更开的起点起。"}],"memoryTip":"/aɪ/ 先开大口，/eɪ/ 起点更收。"}', 7, TRUE),
('unit_compare_08', 'phoneme-compare', 'PHONEME_COMPARE', '双元音 /əʊ/ 与 /aʊ/', '{"category":"双元音对比","title":"/əʊ/ 和 /aʊ/","description":"两者结尾都收向圆唇，/əʊ/ 起点放松，/aʊ/ 起点开口更大。","phonemes":[{"phonemeId":"p_v_16","ipa":"/əʊ/","description":"英式从中央元音起步，逐渐收圆。","mouth":{"type":"relaxed"},"audioUrl":null,"examples":["go","coat","low"]},{"phonemeId":"p_v_17","ipa":"/aʊ/","description":"先打开口腔，再滑向 /ʊ/。","mouth":{"type":"open"},"audioUrl":null,"examples":["now","out","loud"]}],"audioPairs":[{"left":"coat","right":"count","tip":"count 起点开口更大。"},{"left":"low","right":"loud","tip":"low 起点更轻，loud 起点更开。"}],"memoryTip":"/aʊ/ 先开再收，/əʊ/ 更轻更圆滑。"}', 8, TRUE),
('unit_compare_09', 'phoneme-compare', 'PHONEME_COMPARE', '清 /p/ 与浊 /b/', '{"category":"清浊辅音对比","title":"/p/ 和 /b/","description":"双唇动作相同，区别在声带是否振动。","phonemes":[{"phonemeId":"p_3","ipa":"/p/","description":"清双唇爆破音，声带不振动，词首常有送气。","mouth":{"type":"closed"},"audioUrl":null,"examples":["pat","pin","cap"]},{"phonemeId":"p_c_02","ipa":"/b/","description":"浊双唇爆破音，声带振动。","mouth":{"type":"closed"},"audioUrl":null,"examples":["bat","bin","cab"]}],"audioPairs":[{"left":"pat","right":"bat","tip":"摸喉咙，bat 开头有振动。"},{"left":"pin","right":"bin","tip":"pin 只有气流爆破，bin 带声音。"}],"memoryTip":"同样闭双唇，区别放在喉咙振动上。"}', 9, TRUE),
('unit_compare_10', 'phoneme-compare', 'PHONEME_COMPARE', '清 /t/ 与浊 /d/', '{"category":"清浊辅音对比","title":"/t/ 和 /d/","description":"舌尖位置相同，/t/ 清，/d/ 浊。","phonemes":[{"phonemeId":"p_c_03","ipa":"/t/","description":"清齿龈爆破音，声带不振动。","mouth":{"type":"relaxed"},"audioUrl":null,"examples":["ten","to","late"]},{"phonemeId":"p_c_04","ipa":"/d/","description":"浊齿龈爆破音，声带振动。","mouth":{"type":"relaxed"},"audioUrl":null,"examples":["den","do","laid"]}],"audioPairs":[{"left":"ten","right":"den","tip":"den 开头更有声带振动。"},{"left":"to","right":"do","tip":"to 是清爆破，do 是浊爆破。"}],"memoryTip":"舌尖都抵齿龈，清浊靠喉咙判断。"}', 10, TRUE),
('unit_compare_11', 'phoneme-compare', 'PHONEME_COMPARE', '清 /k/ 与浊 /ɡ/', '{"category":"清浊辅音对比","title":"/k/ 和 /ɡ/","description":"发力点都在软腭，区别是 /k/ 不振动，/ɡ/ 振动。","phonemes":[{"phonemeId":"p_c_05","ipa":"/k/","description":"清软腭爆破音，气流短促释放。","mouth":{"type":"relaxed"},"audioUrl":null,"examples":["coat","curl","back"]},{"phonemeId":"p_c_06","ipa":"/ɡ/","description":"浊软腭爆破音，声带振动。","mouth":{"type":"relaxed"},"audioUrl":null,"examples":["goat","girl","bag"]}],"audioPairs":[{"left":"coat","right":"goat","tip":"goat 开头带声带振动。"},{"left":"curl","right":"girl","tip":"两个音都在口腔后部，听清浊。"}],"memoryTip":"发音位置不变，只切换声带状态。"}', 11, TRUE),
('unit_compare_12', 'phoneme-compare', 'PHONEME_COMPARE', '清 /f/ 与浊 /v/', '{"category":"清浊辅音对比","title":"/f/ 和 /v/","description":"上齿轻触下唇，/f/ 只有气流，/v/ 带声带振动。","phonemes":[{"phonemeId":"p_c_07","ipa":"/f/","description":"清唇齿摩擦音，声带不振动。","mouth":{"type":"relaxed"},"audioUrl":null,"examples":["fan","fine","leaf"]},{"phonemeId":"p_c_08","ipa":"/v/","description":"浊唇齿摩擦音，口型像 /f/，但有振动。","mouth":{"type":"relaxed"},"audioUrl":null,"examples":["van","vine","leave"]}],"audioPairs":[{"left":"fan","right":"van","tip":"van 开头喉咙会振动。"},{"left":"fine","right":"vine","tip":"口型不变，只换清浊。"}],"memoryTip":"不要咬下唇，轻触后用声带区分。"}', 12, TRUE),
('unit_compare_13', 'phoneme-compare', 'PHONEME_COMPARE', '清 /s/ 与浊 /z/', '{"category":"清浊辅音对比","title":"/s/ 和 /z/","description":"舌尖接近齿龈形成窄缝，/s/ 清，/z/ 浊。","phonemes":[{"phonemeId":"p_c_11","ipa":"/s/","description":"清齿龈摩擦音，气流细而清。","mouth":{"type":"relaxed"},"audioUrl":null,"examples":["sip","seal","rice"]},{"phonemeId":"p_c_12","ipa":"/z/","description":"浊齿龈摩擦音，可以持续听到振动。","mouth":{"type":"relaxed"},"audioUrl":null,"examples":["zip","zeal","rise"]}],"audioPairs":[{"left":"sip","right":"zip","tip":"zip 开头有明显振动。"},{"left":"rice","right":"rise","tip":"词尾 /s/ 清，/z/ 浊。"}],"memoryTip":"把音拉长，能振动的是 /z/。"}', 13, TRUE),
('unit_compare_14', 'phoneme-compare', 'PHONEME_COMPARE', '清 /θ/ 与浊 /ð/', '{"category":"清浊辅音对比","title":"/θ/ 和 /ð/","description":"舌尖都靠近齿间，/θ/ 清，/ð/ 浊。","phonemes":[{"phonemeId":"p_c_09","ipa":"/θ/","description":"清齿间摩擦音，只有气流摩擦。","mouth":{"type":"relaxed"},"audioUrl":null,"examples":["think","thin","bath"]},{"phonemeId":"p_c_10","ipa":"/ð/","description":"浊齿间摩擦音，带声带振动。","mouth":{"type":"relaxed"},"audioUrl":null,"examples":["this","then","bathe"]}],"audioPairs":[{"left":"thin","right":"then","tip":"then 开头是浊音，喉咙振动。"},{"left":"bath","right":"bathe","tip":"bath 词尾清，bathe 词尾浊。"}],"memoryTip":"先摆齿间舌位，再用声带区分。"}', 14, TRUE),
('unit_compare_15', 'phoneme-compare', 'PHONEME_COMPARE', '清 /ʃ/ 与浊 /ʒ/', '{"category":"清浊辅音对比","title":"/ʃ/ 和 /ʒ/","description":"两者口型接近，舌位偏后且嘴唇略圆，区别仍是清浊。","phonemes":[{"phonemeId":"p_c_13","ipa":"/ʃ/","description":"清腭龈摩擦音，像 sh，声带不振动。","mouth":{"type":"closed"},"audioUrl":null,"examples":["she","pressure","wash"]},{"phonemeId":"p_c_14","ipa":"/ʒ/","description":"浊腭龈摩擦音，常见于 vision、measure。","mouth":{"type":"closed"},"audioUrl":null,"examples":["vision","measure","beige"]}],"audioPairs":[{"left":"pressure","right":"pleasure","tip":"pleasure 中间是浊 /ʒ/。"},{"left":"Confucian","right":"confusion","tip":"confusion 中间带 /ʒ/ 的振动。"}],"memoryTip":"/ʒ/ 不常在词首，遇到 vision、measure 先听浊摩擦。"}', 15, TRUE),
('unit_compare_16', 'phoneme-compare', 'PHONEME_COMPARE', '清 /tʃ/ 与浊 /dʒ/', '{"category":"清浊辅音对比","title":"/tʃ/ 和 /dʒ/","description":"两者都是破擦音，先阻塞再摩擦；/tʃ/ 清，/dʒ/ 浊。","phonemes":[{"phonemeId":"p_c_16","ipa":"/tʃ/","description":"清破擦音，先像 /t/，再释放成 /ʃ/。","mouth":{"type":"closed"},"audioUrl":null,"examples":["choke","cheer","batch"]},{"phonemeId":"p_c_17","ipa":"/dʒ/","description":"浊破擦音，先像 /d/，再释放成 /ʒ/。","mouth":{"type":"closed"},"audioUrl":null,"examples":["joke","jeer","badge"]}],"audioPairs":[{"left":"choke","right":"joke","tip":"joke 开头有声带振动。"},{"left":"cheer","right":"jeer","tip":"两者释放方式相近，重点听清浊。"}],"memoryTip":"把 /tʃ/ 和 /dʒ/ 当成一对清浊破擦音练。"}', 16, TRUE);
