DELETE FROM quiz_submissions WHERE question_id LIKE 'q_syllable_%';
DELETE FROM quiz_options WHERE question_id LIKE 'q_syllable_%';
DELETE FROM quiz_questions WHERE id LIKE 'q_syllable_%';
DELETE FROM learning_units WHERE id LIKE 'unit_syllable_%';

INSERT INTO learning_units (id, template_code, content_type, title, content_json, sort_order, enabled) VALUES
('unit_syllable_01', 'syllable', 'SYLLABLE', '音素音节 · market', '{"rules":["count syllables","Find the vowel core first, then check stress and endings."],"word":"market","lessonTitle":"音素音节 · market","question":{"options":[{"id":"A","label":"1"},{"id":"B","label":"2"},{"id":"C","label":"3"},{"id":"D","label":"4"}],"prompt":"What is the key answer for market?","questionId":"q_syllable_01"},"description":"Practice count syllables with market","memoryTip":"Count vowel sounds, not letters.","ipa":"/ˈmɑːkɪt/","segments":["mar","ket"]}', 1, TRUE),
('unit_syllable_02', 'syllable', 'SYLLABLE', '音素音节 · garden', '{"rules":["count syllables","Find the vowel core first, then check stress and endings."],"word":"garden","lessonTitle":"音素音节 · garden","question":{"options":[{"id":"A","label":"1"},{"id":"B","label":"2"},{"id":"C","label":"3"},{"id":"D","label":"4"}],"prompt":"What is the key answer for garden?","questionId":"q_syllable_02"},"description":"Practice count syllables with garden","memoryTip":"Count vowel sounds, not letters.","ipa":"/ˈɡɑːdn/","segments":["gar","den"]}', 2, TRUE),
('unit_syllable_03', 'syllable', 'SYLLABLE', '音素音节 · window', '{"rules":["count syllables","Find the vowel core first, then check stress and endings."],"word":"window","lessonTitle":"音素音节 · window","question":{"options":[{"id":"A","label":"1"},{"id":"B","label":"2"},{"id":"C","label":"3"},{"id":"D","label":"4"}],"prompt":"What is the key answer for window?","questionId":"q_syllable_03"},"description":"Practice count syllables with window","memoryTip":"Count vowel sounds, not letters.","ipa":"/ˈwɪndəʊ/","segments":["win","dow"]}', 3, TRUE),
('unit_syllable_04', 'syllable', 'SYLLABLE', '音素音节 · pencil', '{"rules":["count syllables","Find the vowel core first, then check stress and endings."],"word":"pencil","lessonTitle":"音素音节 · pencil","question":{"options":[{"id":"A","label":"1"},{"id":"B","label":"2"},{"id":"C","label":"3"},{"id":"D","label":"4"}],"prompt":"What is the key answer for pencil?","questionId":"q_syllable_04"},"description":"Practice count syllables with pencil","memoryTip":"Count vowel sounds, not letters.","ipa":"/ˈpensl/","segments":["pen","cil"]}', 4, TRUE),
('unit_syllable_05', 'syllable', 'SYLLABLE', '音素音节 · computer', '{"rules":["vowel core","Find the vowel core first, then check stress and endings."],"word":"computer","lessonTitle":"音素音节 · computer","question":{"options":[{"id":"A","label":"second syllable"},{"id":"B","label":"first syllable"},{"id":"C","label":"third syllable"},{"id":"D","label":"other 3"}],"prompt":"What is the key answer for computer?","questionId":"q_syllable_05"},"description":"Practice vowel core with computer","memoryTip":"Count vowel sounds, not letters.","ipa":"/kəmˈpjuːtə/","segments":["com","pu","ter"]}', 5, TRUE),
('unit_syllable_06', 'syllable', 'SYLLABLE', '音素音节 · banana', '{"rules":["vowel core","Find the vowel core first, then check stress and endings."],"word":"banana","lessonTitle":"音素音节 · banana","question":{"options":[{"id":"A","label":"second syllable"},{"id":"B","label":"first syllable"},{"id":"C","label":"third syllable"},{"id":"D","label":"other 3"}],"prompt":"What is the key answer for banana?","questionId":"q_syllable_06"},"description":"Practice vowel core with banana","memoryTip":"Count vowel sounds, not letters.","ipa":"/bəˈnɑːnə/","segments":["ba","na","na"]}', 6, TRUE),
('unit_syllable_07', 'syllable', 'SYLLABLE', '音素音节 · family', '{"rules":["vowel core","Find the vowel core first, then check stress and endings."],"word":"family","lessonTitle":"音素音节 · family","question":{"options":[{"id":"A","label":"first syllable"},{"id":"B","label":"second syllable"},{"id":"C","label":"third syllable"},{"id":"D","label":"other 3"}],"prompt":"What is the key answer for family?","questionId":"q_syllable_07"},"description":"Practice vowel core with family","memoryTip":"Count vowel sounds, not letters.","ipa":"/ˈfæməli/","segments":["fam","i","ly"]}', 7, TRUE),
('unit_syllable_08', 'syllable', 'SYLLABLE', '音素音节 · tomato', '{"rules":["vowel core","Find the vowel core first, then check stress and endings."],"word":"tomato","lessonTitle":"音素音节 · tomato","question":{"options":[{"id":"A","label":"second syllable"},{"id":"B","label":"first syllable"},{"id":"C","label":"third syllable"},{"id":"D","label":"other 3"}],"prompt":"What is the key answer for tomato?","questionId":"q_syllable_08"},"description":"Practice vowel core with tomato","memoryTip":"Count vowel sounds, not letters.","ipa":"/təˈmɑːtəʊ/","segments":["to","ma","to"]}', 8, TRUE),
('unit_syllable_09', 'syllable', 'SYLLABLE', '音素音节 · holiday', '{"rules":["syllable split","Find the vowel core first, then check stress and endings."],"word":"holiday","lessonTitle":"音素音节 · holiday","question":{"options":[{"id":"A","label":"hol-i-day"},{"id":"B","label":"first syllable"},{"id":"C","label":"second syllable"},{"id":"D","label":"third syllable"}],"prompt":"What is the key answer for holiday?","questionId":"q_syllable_09"},"description":"Practice syllable split with holiday","memoryTip":"Count vowel sounds, not letters.","ipa":"/ˈhɒlədeɪ/","segments":["hol","i","day"]}', 9, TRUE),
('unit_syllable_10', 'syllable', 'SYLLABLE', '音素音节 · animal', '{"rules":["syllable split","Find the vowel core first, then check stress and endings."],"word":"animal","lessonTitle":"音素音节 · animal","question":{"options":[{"id":"A","label":"an-i-mal"},{"id":"B","label":"first syllable"},{"id":"C","label":"second syllable"},{"id":"D","label":"third syllable"}],"prompt":"What is the key answer for animal?","questionId":"q_syllable_10"},"description":"Practice syllable split with animal","memoryTip":"Count vowel sounds, not letters.","ipa":"/ˈænɪml/","segments":["an","i","mal"]}', 10, TRUE),
('unit_syllable_11', 'syllable', 'SYLLABLE', '音素音节 · memory', '{"rules":["syllable split","Find the vowel core first, then check stress and endings."],"word":"memory","lessonTitle":"音素音节 · memory","question":{"options":[{"id":"A","label":"mem-o-ry"},{"id":"B","label":"first syllable"},{"id":"C","label":"second syllable"},{"id":"D","label":"third syllable"}],"prompt":"What is the key answer for memory?","questionId":"q_syllable_11"},"description":"Practice syllable split with memory","memoryTip":"Count vowel sounds, not letters.","ipa":"/ˈmeməri/","segments":["mem","o","ry"]}', 11, TRUE),
('unit_syllable_12', 'syllable', 'SYLLABLE', '音素音节 · camera', '{"rules":["syllable split","Find the vowel core first, then check stress and endings."],"word":"camera","lessonTitle":"音素音节 · camera","question":{"options":[{"id":"A","label":"cam-e-ra"},{"id":"B","label":"first syllable"},{"id":"C","label":"second syllable"},{"id":"D","label":"third syllable"}],"prompt":"What is the key answer for camera?","questionId":"q_syllable_12"},"description":"Practice syllable split with camera","memoryTip":"Count vowel sounds, not letters.","ipa":"/ˈkæmərə/","segments":["cam","e","ra"]}', 12, TRUE),
('unit_syllable_13', 'syllable', 'SYLLABLE', '音素音节 · important', '{"rules":["main stress","Find the vowel core first, then check stress and endings."],"word":"important","lessonTitle":"音素音节 · important","question":{"options":[{"id":"A","label":"second syllable"},{"id":"B","label":"first syllable"},{"id":"C","label":"third syllable"},{"id":"D","label":"other 3"}],"prompt":"What is the key answer for important?","questionId":"q_syllable_13"},"description":"Practice main stress with important","memoryTip":"Count vowel sounds, not letters.","ipa":"/ɪmˈpɔːtənt/","segments":["im","por","tant"]}', 13, TRUE),
('unit_syllable_14', 'syllable', 'SYLLABLE', '音素音节 · different', '{"rules":["main stress","Find the vowel core first, then check stress and endings."],"word":"different","lessonTitle":"音素音节 · different","question":{"options":[{"id":"A","label":"first syllable"},{"id":"B","label":"second syllable"},{"id":"C","label":"third syllable"},{"id":"D","label":"other 3"}],"prompt":"What is the key answer for different?","questionId":"q_syllable_14"},"description":"Practice main stress with different","memoryTip":"Count vowel sounds, not letters.","ipa":"/ˈdɪfrənt/","segments":["dif","fer","ent"]}', 14, TRUE),
('unit_syllable_15', 'syllable', 'SYLLABLE', '音素音节 · remember', '{"rules":["main stress","Find the vowel core first, then check stress and endings."],"word":"remember","lessonTitle":"音素音节 · remember","question":{"options":[{"id":"A","label":"second syllable"},{"id":"B","label":"first syllable"},{"id":"C","label":"third syllable"},{"id":"D","label":"other 3"}],"prompt":"What is the key answer for remember?","questionId":"q_syllable_15"},"description":"Practice main stress with remember","memoryTip":"Count vowel sounds, not letters.","ipa":"/rɪˈmembə/","segments":["re","mem","ber"]}', 15, TRUE),
('unit_syllable_16', 'syllable', 'SYLLABLE', '音素音节 · beautiful', '{"rules":["main stress","Find the vowel core first, then check stress and endings."],"word":"beautiful","lessonTitle":"音素音节 · beautiful","question":{"options":[{"id":"A","label":"first syllable"},{"id":"B","label":"second syllable"},{"id":"C","label":"third syllable"},{"id":"D","label":"other 3"}],"prompt":"What is the key answer for beautiful?","questionId":"q_syllable_16"},"description":"Practice main stress with beautiful","memoryTip":"Count vowel sounds, not letters.","ipa":"/ˈbjuːtɪfl/","segments":["beau","ti","ful"]}', 16, TRUE),
('unit_syllable_17', 'syllable', 'SYLLABLE', '音素音节 · music', '{"rules":["open or closed syllable","Find the vowel core first, then check stress and endings."],"word":"music","lessonTitle":"音素音节 · music","question":{"options":[{"id":"A","label":"open syllable"},{"id":"B","label":"first syllable"},{"id":"C","label":"second syllable"},{"id":"D","label":"third syllable"}],"prompt":"What is the key answer for music?","questionId":"q_syllable_17"},"description":"Practice open or closed syllable with music","memoryTip":"Count vowel sounds, not letters.","ipa":"/ˈmjuːzɪk/","segments":["mu","sic"]}', 17, TRUE),
('unit_syllable_18', 'syllable', 'SYLLABLE', '音素音节 · rabbit', '{"rules":["open or closed syllable","Find the vowel core first, then check stress and endings."],"word":"rabbit","lessonTitle":"音素音节 · rabbit","question":{"options":[{"id":"A","label":"closed syllable"},{"id":"B","label":"first syllable"},{"id":"C","label":"second syllable"},{"id":"D","label":"third syllable"}],"prompt":"What is the key answer for rabbit?","questionId":"q_syllable_18"},"description":"Practice open or closed syllable with rabbit","memoryTip":"Count vowel sounds, not letters.","ipa":"/ˈræbɪt/","segments":["rab","bit"]}', 18, TRUE),
('unit_syllable_19', 'syllable', 'SYLLABLE', '音素音节 · paper', '{"rules":["open or closed syllable","Find the vowel core first, then check stress and endings."],"word":"paper","lessonTitle":"音素音节 · paper","question":{"options":[{"id":"A","label":"open syllable"},{"id":"B","label":"first syllable"},{"id":"C","label":"second syllable"},{"id":"D","label":"third syllable"}],"prompt":"What is the key answer for paper?","questionId":"q_syllable_19"},"description":"Practice open or closed syllable with paper","memoryTip":"Count vowel sounds, not letters.","ipa":"/ˈpeɪpə/","segments":["pa","per"]}', 19, TRUE),
('unit_syllable_20', 'syllable', 'SYLLABLE', '音素音节 · traffic', '{"rules":["open or closed syllable","Find the vowel core first, then check stress and endings."],"word":"traffic","lessonTitle":"音素音节 · traffic","question":{"options":[{"id":"A","label":"closed syllable"},{"id":"B","label":"first syllable"},{"id":"C","label":"second syllable"},{"id":"D","label":"third syllable"}],"prompt":"What is the key answer for traffic?","questionId":"q_syllable_20"},"description":"Practice open or closed syllable with traffic","memoryTip":"Count vowel sounds, not letters.","ipa":"/ˈtræfɪk/","segments":["traf","fic"]}', 20, TRUE),
('unit_syllable_21', 'syllable', 'SYLLABLE', '音素音节 · station', '{"rules":["word ending syllable","Find the vowel core first, then check stress and endings."],"word":"station","lessonTitle":"音素音节 · station","question":{"options":[{"id":"A","label":"-tion forms /ʃn/"},{"id":"B","label":"first syllable"},{"id":"C","label":"second syllable"},{"id":"D","label":"third syllable"}],"prompt":"What is the key answer for station?","questionId":"q_syllable_21"},"description":"Practice word ending syllable with station","memoryTip":"Count vowel sounds, not letters.","ipa":"/ˈsteɪʃn/","segments":["sta","tion"]}', 21, TRUE),
('unit_syllable_22', 'syllable', 'SYLLABLE', '音素音节 · little', '{"rules":["word ending syllable","Find the vowel core first, then check stress and endings."],"word":"little","lessonTitle":"音素音节 · little","question":{"options":[{"id":"A","label":"-le ending"},{"id":"B","label":"first syllable"},{"id":"C","label":"second syllable"},{"id":"D","label":"third syllable"}],"prompt":"What is the key answer for little?","questionId":"q_syllable_22"},"description":"Practice word ending syllable with little","memoryTip":"Count vowel sounds, not letters.","ipa":"/ˈlɪtl/","segments":["lit","tle"]}', 22, TRUE),
('unit_syllable_23', 'syllable', 'SYLLABLE', '音素音节 · table', '{"rules":["word ending syllable","Find the vowel core first, then check stress and endings."],"word":"table","lessonTitle":"音素音节 · table","question":{"options":[{"id":"A","label":"-ble ending"},{"id":"B","label":"first syllable"},{"id":"C","label":"second syllable"},{"id":"D","label":"third syllable"}],"prompt":"What is the key answer for table?","questionId":"q_syllable_23"},"description":"Practice word ending syllable with table","memoryTip":"Count vowel sounds, not letters.","ipa":"/ˈteɪbl/","segments":["ta","ble"]}', 23, TRUE),
('unit_syllable_24', 'syllable', 'SYLLABLE', '音素音节 · question', '{"rules":["word ending syllable","Find the vowel core first, then check stress and endings."],"word":"question","lessonTitle":"音素音节 · question","question":{"options":[{"id":"A","label":"-tion sounds /tʃən/"},{"id":"B","label":"first syllable"},{"id":"C","label":"second syllable"},{"id":"D","label":"third syllable"}],"prompt":"What is the key answer for question?","questionId":"q_syllable_24"},"description":"Practice word ending syllable with question","memoryTip":"Count vowel sounds, not letters.","ipa":"/ˈkwestʃən/","segments":["ques","tion"]}', 24, TRUE);

INSERT INTO quiz_questions (id, template_code, unit_id, prompt, explanation) VALUES
('q_syllable_01', 'syllable', 'unit_syllable_01', 'What is the key answer for market?', 'Answer: 2'),
('q_syllable_02', 'syllable', 'unit_syllable_02', 'What is the key answer for garden?', 'Answer: 2'),
('q_syllable_03', 'syllable', 'unit_syllable_03', 'What is the key answer for window?', 'Answer: 2'),
('q_syllable_04', 'syllable', 'unit_syllable_04', 'What is the key answer for pencil?', 'Answer: 2'),
('q_syllable_05', 'syllable', 'unit_syllable_05', 'What is the key answer for computer?', 'Answer: second syllable'),
('q_syllable_06', 'syllable', 'unit_syllable_06', 'What is the key answer for banana?', 'Answer: second syllable'),
('q_syllable_07', 'syllable', 'unit_syllable_07', 'What is the key answer for family?', 'Answer: first syllable'),
('q_syllable_08', 'syllable', 'unit_syllable_08', 'What is the key answer for tomato?', 'Answer: second syllable'),
('q_syllable_09', 'syllable', 'unit_syllable_09', 'What is the key answer for holiday?', 'Answer: hol-i-day'),
('q_syllable_10', 'syllable', 'unit_syllable_10', 'What is the key answer for animal?', 'Answer: an-i-mal'),
('q_syllable_11', 'syllable', 'unit_syllable_11', 'What is the key answer for memory?', 'Answer: mem-o-ry'),
('q_syllable_12', 'syllable', 'unit_syllable_12', 'What is the key answer for camera?', 'Answer: cam-e-ra'),
('q_syllable_13', 'syllable', 'unit_syllable_13', 'What is the key answer for important?', 'Answer: second syllable'),
('q_syllable_14', 'syllable', 'unit_syllable_14', 'What is the key answer for different?', 'Answer: first syllable'),
('q_syllable_15', 'syllable', 'unit_syllable_15', 'What is the key answer for remember?', 'Answer: second syllable'),
('q_syllable_16', 'syllable', 'unit_syllable_16', 'What is the key answer for beautiful?', 'Answer: first syllable'),
('q_syllable_17', 'syllable', 'unit_syllable_17', 'What is the key answer for music?', 'Answer: open syllable'),
('q_syllable_18', 'syllable', 'unit_syllable_18', 'What is the key answer for rabbit?', 'Answer: closed syllable'),
('q_syllable_19', 'syllable', 'unit_syllable_19', 'What is the key answer for paper?', 'Answer: open syllable'),
('q_syllable_20', 'syllable', 'unit_syllable_20', 'What is the key answer for traffic?', 'Answer: closed syllable'),
('q_syllable_21', 'syllable', 'unit_syllable_21', 'What is the key answer for station?', 'Answer: -tion forms /ʃn/'),
('q_syllable_22', 'syllable', 'unit_syllable_22', 'What is the key answer for little?', 'Answer: -le ending'),
('q_syllable_23', 'syllable', 'unit_syllable_23', 'What is the key answer for table?', 'Answer: -ble ending'),
('q_syllable_24', 'syllable', 'unit_syllable_24', 'What is the key answer for question?', 'Answer: -tion sounds /tʃən/');

INSERT INTO quiz_options (id, question_id, option_code, label, correct, sort_order) VALUES
('qo_syllable_01_a', 'q_syllable_01', 'A', '1', FALSE, 1),
('qo_syllable_01_b', 'q_syllable_01', 'B', '2', TRUE, 2),
('qo_syllable_01_c', 'q_syllable_01', 'C', '3', FALSE, 3),
('qo_syllable_01_d', 'q_syllable_01', 'D', '4', FALSE, 4),
('qo_syllable_02_a', 'q_syllable_02', 'A', '1', FALSE, 1),
('qo_syllable_02_b', 'q_syllable_02', 'B', '2', TRUE, 2),
('qo_syllable_02_c', 'q_syllable_02', 'C', '3', FALSE, 3),
('qo_syllable_02_d', 'q_syllable_02', 'D', '4', FALSE, 4),
('qo_syllable_03_a', 'q_syllable_03', 'A', '1', FALSE, 1),
('qo_syllable_03_b', 'q_syllable_03', 'B', '2', TRUE, 2),
('qo_syllable_03_c', 'q_syllable_03', 'C', '3', FALSE, 3),
('qo_syllable_03_d', 'q_syllable_03', 'D', '4', FALSE, 4),
('qo_syllable_04_a', 'q_syllable_04', 'A', '1', FALSE, 1),
('qo_syllable_04_b', 'q_syllable_04', 'B', '2', TRUE, 2),
('qo_syllable_04_c', 'q_syllable_04', 'C', '3', FALSE, 3),
('qo_syllable_04_d', 'q_syllable_04', 'D', '4', FALSE, 4),
('qo_syllable_05_a', 'q_syllable_05', 'A', 'second syllable', TRUE, 1),
('qo_syllable_05_b', 'q_syllable_05', 'B', 'first syllable', FALSE, 2),
('qo_syllable_05_c', 'q_syllable_05', 'C', 'third syllable', FALSE, 3),
('qo_syllable_05_d', 'q_syllable_05', 'D', 'other 3', FALSE, 4),
('qo_syllable_06_a', 'q_syllable_06', 'A', 'second syllable', TRUE, 1),
('qo_syllable_06_b', 'q_syllable_06', 'B', 'first syllable', FALSE, 2),
('qo_syllable_06_c', 'q_syllable_06', 'C', 'third syllable', FALSE, 3),
('qo_syllable_06_d', 'q_syllable_06', 'D', 'other 3', FALSE, 4),
('qo_syllable_07_a', 'q_syllable_07', 'A', 'first syllable', TRUE, 1),
('qo_syllable_07_b', 'q_syllable_07', 'B', 'second syllable', FALSE, 2),
('qo_syllable_07_c', 'q_syllable_07', 'C', 'third syllable', FALSE, 3),
('qo_syllable_07_d', 'q_syllable_07', 'D', 'other 3', FALSE, 4),
('qo_syllable_08_a', 'q_syllable_08', 'A', 'second syllable', TRUE, 1),
('qo_syllable_08_b', 'q_syllable_08', 'B', 'first syllable', FALSE, 2),
('qo_syllable_08_c', 'q_syllable_08', 'C', 'third syllable', FALSE, 3),
('qo_syllable_08_d', 'q_syllable_08', 'D', 'other 3', FALSE, 4),
('qo_syllable_09_a', 'q_syllable_09', 'A', 'hol-i-day', TRUE, 1),
('qo_syllable_09_b', 'q_syllable_09', 'B', 'first syllable', FALSE, 2),
('qo_syllable_09_c', 'q_syllable_09', 'C', 'second syllable', FALSE, 3),
('qo_syllable_09_d', 'q_syllable_09', 'D', 'third syllable', FALSE, 4),
('qo_syllable_10_a', 'q_syllable_10', 'A', 'an-i-mal', TRUE, 1),
('qo_syllable_10_b', 'q_syllable_10', 'B', 'first syllable', FALSE, 2),
('qo_syllable_10_c', 'q_syllable_10', 'C', 'second syllable', FALSE, 3),
('qo_syllable_10_d', 'q_syllable_10', 'D', 'third syllable', FALSE, 4),
('qo_syllable_11_a', 'q_syllable_11', 'A', 'mem-o-ry', TRUE, 1),
('qo_syllable_11_b', 'q_syllable_11', 'B', 'first syllable', FALSE, 2),
('qo_syllable_11_c', 'q_syllable_11', 'C', 'second syllable', FALSE, 3),
('qo_syllable_11_d', 'q_syllable_11', 'D', 'third syllable', FALSE, 4),
('qo_syllable_12_a', 'q_syllable_12', 'A', 'cam-e-ra', TRUE, 1),
('qo_syllable_12_b', 'q_syllable_12', 'B', 'first syllable', FALSE, 2),
('qo_syllable_12_c', 'q_syllable_12', 'C', 'second syllable', FALSE, 3),
('qo_syllable_12_d', 'q_syllable_12', 'D', 'third syllable', FALSE, 4),
('qo_syllable_13_a', 'q_syllable_13', 'A', 'second syllable', TRUE, 1),
('qo_syllable_13_b', 'q_syllable_13', 'B', 'first syllable', FALSE, 2),
('qo_syllable_13_c', 'q_syllable_13', 'C', 'third syllable', FALSE, 3),
('qo_syllable_13_d', 'q_syllable_13', 'D', 'other 3', FALSE, 4),
('qo_syllable_14_a', 'q_syllable_14', 'A', 'first syllable', TRUE, 1),
('qo_syllable_14_b', 'q_syllable_14', 'B', 'second syllable', FALSE, 2),
('qo_syllable_14_c', 'q_syllable_14', 'C', 'third syllable', FALSE, 3),
('qo_syllable_14_d', 'q_syllable_14', 'D', 'other 3', FALSE, 4),
('qo_syllable_15_a', 'q_syllable_15', 'A', 'second syllable', TRUE, 1),
('qo_syllable_15_b', 'q_syllable_15', 'B', 'first syllable', FALSE, 2),
('qo_syllable_15_c', 'q_syllable_15', 'C', 'third syllable', FALSE, 3),
('qo_syllable_15_d', 'q_syllable_15', 'D', 'other 3', FALSE, 4),
('qo_syllable_16_a', 'q_syllable_16', 'A', 'first syllable', TRUE, 1),
('qo_syllable_16_b', 'q_syllable_16', 'B', 'second syllable', FALSE, 2),
('qo_syllable_16_c', 'q_syllable_16', 'C', 'third syllable', FALSE, 3),
('qo_syllable_16_d', 'q_syllable_16', 'D', 'other 3', FALSE, 4),
('qo_syllable_17_a', 'q_syllable_17', 'A', 'open syllable', TRUE, 1),
('qo_syllable_17_b', 'q_syllable_17', 'B', 'first syllable', FALSE, 2),
('qo_syllable_17_c', 'q_syllable_17', 'C', 'second syllable', FALSE, 3),
('qo_syllable_17_d', 'q_syllable_17', 'D', 'third syllable', FALSE, 4),
('qo_syllable_18_a', 'q_syllable_18', 'A', 'closed syllable', TRUE, 1),
('qo_syllable_18_b', 'q_syllable_18', 'B', 'first syllable', FALSE, 2),
('qo_syllable_18_c', 'q_syllable_18', 'C', 'second syllable', FALSE, 3),
('qo_syllable_18_d', 'q_syllable_18', 'D', 'third syllable', FALSE, 4),
('qo_syllable_19_a', 'q_syllable_19', 'A', 'open syllable', TRUE, 1),
('qo_syllable_19_b', 'q_syllable_19', 'B', 'first syllable', FALSE, 2),
('qo_syllable_19_c', 'q_syllable_19', 'C', 'second syllable', FALSE, 3),
('qo_syllable_19_d', 'q_syllable_19', 'D', 'third syllable', FALSE, 4),
('qo_syllable_20_a', 'q_syllable_20', 'A', 'closed syllable', TRUE, 1),
('qo_syllable_20_b', 'q_syllable_20', 'B', 'first syllable', FALSE, 2),
('qo_syllable_20_c', 'q_syllable_20', 'C', 'second syllable', FALSE, 3),
('qo_syllable_20_d', 'q_syllable_20', 'D', 'third syllable', FALSE, 4),
('qo_syllable_21_a', 'q_syllable_21', 'A', '-tion forms /ʃn/', TRUE, 1),
('qo_syllable_21_b', 'q_syllable_21', 'B', 'first syllable', FALSE, 2),
('qo_syllable_21_c', 'q_syllable_21', 'C', 'second syllable', FALSE, 3),
('qo_syllable_21_d', 'q_syllable_21', 'D', 'third syllable', FALSE, 4),
('qo_syllable_22_a', 'q_syllable_22', 'A', '-le ending', TRUE, 1),
('qo_syllable_22_b', 'q_syllable_22', 'B', 'first syllable', FALSE, 2),
('qo_syllable_22_c', 'q_syllable_22', 'C', 'second syllable', FALSE, 3),
('qo_syllable_22_d', 'q_syllable_22', 'D', 'third syllable', FALSE, 4),
('qo_syllable_23_a', 'q_syllable_23', 'A', '-ble ending', TRUE, 1),
('qo_syllable_23_b', 'q_syllable_23', 'B', 'first syllable', FALSE, 2),
('qo_syllable_23_c', 'q_syllable_23', 'C', 'second syllable', FALSE, 3),
('qo_syllable_23_d', 'q_syllable_23', 'D', 'third syllable', FALSE, 4),
('qo_syllable_24_a', 'q_syllable_24', 'A', '-tion sounds /tʃən/', TRUE, 1),
('qo_syllable_24_b', 'q_syllable_24', 'B', 'first syllable', FALSE, 2),
('qo_syllable_24_c', 'q_syllable_24', 'C', 'second syllable', FALSE, 3),
('qo_syllable_24_d', 'q_syllable_24', 'D', 'third syllable', FALSE, 4);

