INSERT INTO learning_units (id, template_code, content_type, title, content_json, sort_order, enabled) VALUES
('unit_syllable_25', 'syllable', 'SYLLABLE', '音素音节 · library', '{"ipa":"/ˈlaɪbrəri/","word":"library","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · library","rules":["count syllables","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"2","id":"A"},{"label":"3","id":"B"},{"label":"4","id":"C"},{"label":"5","id":"D"}],"prompt":"What is the key answer for library?","questionId":"q_syllable_25"},"description":"Second batch practice: count syllables with library","segments":["li","bra","ry"]}', 25, TRUE),
('unit_syllable_26', 'syllable', 'SYLLABLE', '音素音节 · hospital', '{"ipa":"/ˈhɒspɪtl/","word":"hospital","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · hospital","rules":["count syllables","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"2","id":"A"},{"label":"3","id":"B"},{"label":"4","id":"C"},{"label":"5","id":"D"}],"prompt":"What is the key answer for hospital?","questionId":"q_syllable_26"},"description":"Second batch practice: count syllables with hospital","segments":["hos","pi","tal"]}', 26, TRUE),
('unit_syllable_27', 'syllable', 'SYLLABLE', '音素音节 · chocolate', '{"ipa":"/ˈtʃɒklət/","word":"chocolate","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · chocolate","rules":["count syllables","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"2","id":"A"},{"label":"3","id":"B"},{"label":"4","id":"C"},{"label":"5","id":"D"}],"prompt":"What is the key answer for chocolate?","questionId":"q_syllable_27"},"description":"Second batch practice: count syllables with chocolate","segments":["choc","o","late"]}', 27, TRUE),
('unit_syllable_28', 'syllable', 'SYLLABLE', '音素音节 · elephant', '{"ipa":"/ˈelɪfənt/","word":"elephant","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · elephant","rules":["count syllables","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"2","id":"A"},{"label":"3","id":"B"},{"label":"4","id":"C"},{"label":"5","id":"D"}],"prompt":"What is the key answer for elephant?","questionId":"q_syllable_28"},"description":"Second batch practice: count syllables with elephant","segments":["el","e","phant"]}', 28, TRUE),
('unit_syllable_29', 'syllable', 'SYLLABLE', '音素音节 · attention', '{"ipa":"/əˈtenʃn/","word":"attention","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · attention","rules":["main stress","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"second syllable","id":"A"},{"label":"first syllable","id":"B"},{"label":"third syllable","id":"C"},{"label":"other 3","id":"D"}],"prompt":"What is the key answer for attention?","questionId":"q_syllable_29"},"description":"Second batch practice: main stress with attention","segments":["a","tten","tion"]}', 29, TRUE),
('unit_syllable_30', 'syllable', 'SYLLABLE', '音素音节 · expensive', '{"ipa":"/ɪkˈspensɪv/","word":"expensive","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · expensive","rules":["main stress","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"second syllable","id":"A"},{"label":"first syllable","id":"B"},{"label":"third syllable","id":"C"},{"label":"other 3","id":"D"}],"prompt":"What is the key answer for expensive?","questionId":"q_syllable_30"},"description":"Second batch practice: main stress with expensive","segments":["ex","pen","sive"]}', 30, TRUE),
('unit_syllable_31', 'syllable', 'SYLLABLE', '音素音节 · popular', '{"ipa":"/ˈpɒpjələ/","word":"popular","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · popular","rules":["main stress","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"first syllable","id":"A"},{"label":"second syllable","id":"B"},{"label":"third syllable","id":"C"},{"label":"other 3","id":"D"}],"prompt":"What is the key answer for popular?","questionId":"q_syllable_31"},"description":"Second batch practice: main stress with popular","segments":["pop","u","lar"]}', 31, TRUE),
('unit_syllable_32', 'syllable', 'SYLLABLE', '音素音节 · together', '{"ipa":"/təˈɡeðə/","word":"together","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · together","rules":["main stress","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"second syllable","id":"A"},{"label":"first syllable","id":"B"},{"label":"third syllable","id":"C"},{"label":"other 3","id":"D"}],"prompt":"What is the key answer for together?","questionId":"q_syllable_32"},"description":"Second batch practice: main stress with together","segments":["to","geth","er"]}', 32, TRUE),
('unit_syllable_33', 'syllable', 'SYLLABLE', '音素音节 · orange', '{"ipa":"/ˈɒrɪndʒ/","word":"orange","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · orange","rules":["syllable split","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"or-ange","id":"A"},{"label":"first syllable","id":"B"},{"label":"second syllable","id":"C"},{"label":"third syllable","id":"D"}],"prompt":"What is the key answer for orange?","questionId":"q_syllable_33"},"description":"Second batch practice: syllable split with orange","segments":["or","ange"]}', 33, TRUE),
('unit_syllable_34', 'syllable', 'SYLLABLE', '音素音节 · morning', '{"ipa":"/ˈmɔːnɪŋ/","word":"morning","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · morning","rules":["syllable split","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"morn-ing","id":"A"},{"label":"first syllable","id":"B"},{"label":"second syllable","id":"C"},{"label":"third syllable","id":"D"}],"prompt":"What is the key answer for morning?","questionId":"q_syllable_34"},"description":"Second batch practice: syllable split with morning","segments":["morn","ing"]}', 34, TRUE),
('unit_syllable_35', 'syllable', 'SYLLABLE', '音素音节 · lesson', '{"ipa":"/ˈlesn/","word":"lesson","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · lesson","rules":["syllable split","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"les-son","id":"A"},{"label":"first syllable","id":"B"},{"label":"second syllable","id":"C"},{"label":"third syllable","id":"D"}],"prompt":"What is the key answer for lesson?","questionId":"q_syllable_35"},"description":"Second batch practice: syllable split with lesson","segments":["les","son"]}', 35, TRUE),
('unit_syllable_36', 'syllable', 'SYLLABLE', '音素音节 · yellow', '{"ipa":"/ˈjeləʊ/","word":"yellow","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · yellow","rules":["syllable split","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"yel-low","id":"A"},{"label":"first syllable","id":"B"},{"label":"second syllable","id":"C"},{"label":"third syllable","id":"D"}],"prompt":"What is the key answer for yellow?","questionId":"q_syllable_36"},"description":"Second batch practice: syllable split with yellow","segments":["yel","low"]}', 36, TRUE),
('unit_syllable_37', 'syllable', 'SYLLABLE', '音素音节 · basic', '{"ipa":"/ˈbeɪsɪk/","word":"basic","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · basic","rules":["open or closed syllable","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"open syllable","id":"A"},{"label":"first syllable","id":"B"},{"label":"second syllable","id":"C"},{"label":"third syllable","id":"D"}],"prompt":"What is the key answer for basic?","questionId":"q_syllable_37"},"description":"Second batch practice: open or closed syllable with basic","segments":["ba","sic"]}', 37, TRUE),
('unit_syllable_38', 'syllable', 'SYLLABLE', '音素音节 · picnic', '{"ipa":"/ˈpɪknɪk/","word":"picnic","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · picnic","rules":["open or closed syllable","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"closed syllable","id":"A"},{"label":"first syllable","id":"B"},{"label":"second syllable","id":"C"},{"label":"third syllable","id":"D"}],"prompt":"What is the key answer for picnic?","questionId":"q_syllable_38"},"description":"Second batch practice: open or closed syllable with picnic","segments":["pic","nic"]}', 38, TRUE),
('unit_syllable_39', 'syllable', 'SYLLABLE', '音素音节 · silent', '{"ipa":"/ˈsaɪlənt/","word":"silent","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · silent","rules":["open or closed syllable","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"open syllable","id":"A"},{"label":"first syllable","id":"B"},{"label":"second syllable","id":"C"},{"label":"third syllable","id":"D"}],"prompt":"What is the key answer for silent?","questionId":"q_syllable_39"},"description":"Second batch practice: open or closed syllable with silent","segments":["si","lent"]}', 39, TRUE),
('unit_syllable_40', 'syllable', 'SYLLABLE', '音素音节 · basket', '{"ipa":"/ˈbɑːskɪt/","word":"basket","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · basket","rules":["open or closed syllable","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"closed syllable","id":"A"},{"label":"first syllable","id":"B"},{"label":"second syllable","id":"C"},{"label":"third syllable","id":"D"}],"prompt":"What is the key answer for basket?","questionId":"q_syllable_40"},"description":"Second batch practice: open or closed syllable with basket","segments":["bas","ket"]}', 40, TRUE),
('unit_syllable_41', 'syllable', 'SYLLABLE', '音素音节 · action', '{"ipa":"/ˈækʃn/","word":"action","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · action","rules":["word ending syllable","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"-tion forms /ʃn/","id":"A"},{"label":"first syllable","id":"B"},{"label":"second syllable","id":"C"},{"label":"third syllable","id":"D"}],"prompt":"What is the key answer for action?","questionId":"q_syllable_41"},"description":"Second batch practice: word ending syllable with action","segments":["ac","tion"]}', 41, TRUE),
('unit_syllable_42', 'syllable', 'SYLLABLE', '音素音节 · people', '{"ipa":"/ˈpiːpl/","word":"people","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · people","rules":["word ending syllable","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"-ple ending","id":"A"},{"label":"first syllable","id":"B"},{"label":"second syllable","id":"C"},{"label":"third syllable","id":"D"}],"prompt":"What is the key answer for people?","questionId":"q_syllable_42"},"description":"Second batch practice: word ending syllable with people","segments":["peo","ple"]}', 42, TRUE),
('unit_syllable_43', 'syllable', 'SYLLABLE', '音素音节 · middle', '{"ipa":"/ˈmɪdl/","word":"middle","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · middle","rules":["word ending syllable","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"-dle ending","id":"A"},{"label":"first syllable","id":"B"},{"label":"second syllable","id":"C"},{"label":"third syllable","id":"D"}],"prompt":"What is the key answer for middle?","questionId":"q_syllable_43"},"description":"Second batch practice: word ending syllable with middle","segments":["mid","dle"]}', 43, TRUE),
('unit_syllable_44', 'syllable', 'SYLLABLE', '音素音节 · simple', '{"ipa":"/ˈsɪmpl/","word":"simple","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · simple","rules":["word ending syllable","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"-ple ending","id":"A"},{"label":"first syllable","id":"B"},{"label":"second syllable","id":"C"},{"label":"third syllable","id":"D"}],"prompt":"What is the key answer for simple?","questionId":"q_syllable_44"},"description":"Second batch practice: word ending syllable with simple","segments":["sim","ple"]}', 44, TRUE),
('unit_syllable_45', 'syllable', 'SYLLABLE', '音素音节 · interesting', '{"ipa":"/ˈɪntrəstɪŋ/","word":"interesting","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · interesting","rules":["count syllables","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"2","id":"A"},{"label":"3","id":"B"},{"label":"4","id":"C"},{"label":"5","id":"D"}],"prompt":"What is the key answer for interesting?","questionId":"q_syllable_45"},"description":"Second batch practice: count syllables with interesting","segments":["in","ter","est","ing"]}', 45, TRUE),
('unit_syllable_46', 'syllable', 'SYLLABLE', '音素音节 · environment', '{"ipa":"/ɪnˈvaɪrənmənt/","word":"environment","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · environment","rules":["count syllables","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"2","id":"A"},{"label":"3","id":"B"},{"label":"4","id":"C"},{"label":"5","id":"D"}],"prompt":"What is the key answer for environment?","questionId":"q_syllable_46"},"description":"Second batch practice: count syllables with environment","segments":["en","vi","ron","ment"]}', 46, TRUE),
('unit_syllable_47', 'syllable', 'SYLLABLE', '音素音节 · understand', '{"ipa":"/ˌʌndəˈstænd/","word":"understand","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · understand","rules":["main stress","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"third syllable","id":"A"},{"label":"first syllable","id":"B"},{"label":"second syllable","id":"C"},{"label":"other 3","id":"D"}],"prompt":"What is the key answer for understand?","questionId":"q_syllable_47"},"description":"Second batch practice: main stress with understand","segments":["un","der","stand"]}', 47, TRUE),
('unit_syllable_48', 'syllable', 'SYLLABLE', '音素音节 · celebration', '{"ipa":"/ˌselɪˈbreɪʃn/","word":"celebration","memoryTip":"Listen for spoken beats before choosing.","lessonTitle":"音素音节 · celebration","rules":["main stress","Check vowel sounds, stress, and common endings."],"question":{"options":[{"label":"third syllable","id":"A"},{"label":"first syllable","id":"B"},{"label":"second syllable","id":"C"},{"label":"other 3","id":"D"}],"prompt":"What is the key answer for celebration?","questionId":"q_syllable_48"},"description":"Second batch practice: main stress with celebration","segments":["cel","e","bra","tion"]}', 48, TRUE);

INSERT INTO quiz_questions (id, template_code, unit_id, prompt, explanation) VALUES
('q_syllable_25', 'syllable', 'unit_syllable_25', 'What is the key answer for library?', 'Answer: 3'),
('q_syllable_26', 'syllable', 'unit_syllable_26', 'What is the key answer for hospital?', 'Answer: 3'),
('q_syllable_27', 'syllable', 'unit_syllable_27', 'What is the key answer for chocolate?', 'Answer: 3'),
('q_syllable_28', 'syllable', 'unit_syllable_28', 'What is the key answer for elephant?', 'Answer: 3'),
('q_syllable_29', 'syllable', 'unit_syllable_29', 'What is the key answer for attention?', 'Answer: second syllable'),
('q_syllable_30', 'syllable', 'unit_syllable_30', 'What is the key answer for expensive?', 'Answer: second syllable'),
('q_syllable_31', 'syllable', 'unit_syllable_31', 'What is the key answer for popular?', 'Answer: first syllable'),
('q_syllable_32', 'syllable', 'unit_syllable_32', 'What is the key answer for together?', 'Answer: second syllable'),
('q_syllable_33', 'syllable', 'unit_syllable_33', 'What is the key answer for orange?', 'Answer: or-ange'),
('q_syllable_34', 'syllable', 'unit_syllable_34', 'What is the key answer for morning?', 'Answer: morn-ing'),
('q_syllable_35', 'syllable', 'unit_syllable_35', 'What is the key answer for lesson?', 'Answer: les-son'),
('q_syllable_36', 'syllable', 'unit_syllable_36', 'What is the key answer for yellow?', 'Answer: yel-low'),
('q_syllable_37', 'syllable', 'unit_syllable_37', 'What is the key answer for basic?', 'Answer: open syllable'),
('q_syllable_38', 'syllable', 'unit_syllable_38', 'What is the key answer for picnic?', 'Answer: closed syllable'),
('q_syllable_39', 'syllable', 'unit_syllable_39', 'What is the key answer for silent?', 'Answer: open syllable'),
('q_syllable_40', 'syllable', 'unit_syllable_40', 'What is the key answer for basket?', 'Answer: closed syllable'),
('q_syllable_41', 'syllable', 'unit_syllable_41', 'What is the key answer for action?', 'Answer: -tion forms /ʃn/'),
('q_syllable_42', 'syllable', 'unit_syllable_42', 'What is the key answer for people?', 'Answer: -ple ending'),
('q_syllable_43', 'syllable', 'unit_syllable_43', 'What is the key answer for middle?', 'Answer: -dle ending'),
('q_syllable_44', 'syllable', 'unit_syllable_44', 'What is the key answer for simple?', 'Answer: -ple ending'),
('q_syllable_45', 'syllable', 'unit_syllable_45', 'What is the key answer for interesting?', 'Answer: 4'),
('q_syllable_46', 'syllable', 'unit_syllable_46', 'What is the key answer for environment?', 'Answer: 4'),
('q_syllable_47', 'syllable', 'unit_syllable_47', 'What is the key answer for understand?', 'Answer: third syllable'),
('q_syllable_48', 'syllable', 'unit_syllable_48', 'What is the key answer for celebration?', 'Answer: third syllable');

INSERT INTO quiz_options (id, question_id, option_code, label, correct, sort_order) VALUES
('qo_syllable_25_a', 'q_syllable_25', 'A', '2', FALSE, 1),
('qo_syllable_25_b', 'q_syllable_25', 'B', '3', TRUE, 2),
('qo_syllable_25_c', 'q_syllable_25', 'C', '4', FALSE, 3),
('qo_syllable_25_d', 'q_syllable_25', 'D', '5', FALSE, 4),
('qo_syllable_26_a', 'q_syllable_26', 'A', '2', FALSE, 1),
('qo_syllable_26_b', 'q_syllable_26', 'B', '3', TRUE, 2),
('qo_syllable_26_c', 'q_syllable_26', 'C', '4', FALSE, 3),
('qo_syllable_26_d', 'q_syllable_26', 'D', '5', FALSE, 4),
('qo_syllable_27_a', 'q_syllable_27', 'A', '2', FALSE, 1),
('qo_syllable_27_b', 'q_syllable_27', 'B', '3', TRUE, 2),
('qo_syllable_27_c', 'q_syllable_27', 'C', '4', FALSE, 3),
('qo_syllable_27_d', 'q_syllable_27', 'D', '5', FALSE, 4),
('qo_syllable_28_a', 'q_syllable_28', 'A', '2', FALSE, 1),
('qo_syllable_28_b', 'q_syllable_28', 'B', '3', TRUE, 2),
('qo_syllable_28_c', 'q_syllable_28', 'C', '4', FALSE, 3),
('qo_syllable_28_d', 'q_syllable_28', 'D', '5', FALSE, 4),
('qo_syllable_29_a', 'q_syllable_29', 'A', 'second syllable', TRUE, 1),
('qo_syllable_29_b', 'q_syllable_29', 'B', 'first syllable', FALSE, 2),
('qo_syllable_29_c', 'q_syllable_29', 'C', 'third syllable', FALSE, 3),
('qo_syllable_29_d', 'q_syllable_29', 'D', 'other 3', FALSE, 4),
('qo_syllable_30_a', 'q_syllable_30', 'A', 'second syllable', TRUE, 1),
('qo_syllable_30_b', 'q_syllable_30', 'B', 'first syllable', FALSE, 2),
('qo_syllable_30_c', 'q_syllable_30', 'C', 'third syllable', FALSE, 3),
('qo_syllable_30_d', 'q_syllable_30', 'D', 'other 3', FALSE, 4),
('qo_syllable_31_a', 'q_syllable_31', 'A', 'first syllable', TRUE, 1),
('qo_syllable_31_b', 'q_syllable_31', 'B', 'second syllable', FALSE, 2),
('qo_syllable_31_c', 'q_syllable_31', 'C', 'third syllable', FALSE, 3),
('qo_syllable_31_d', 'q_syllable_31', 'D', 'other 3', FALSE, 4),
('qo_syllable_32_a', 'q_syllable_32', 'A', 'second syllable', TRUE, 1),
('qo_syllable_32_b', 'q_syllable_32', 'B', 'first syllable', FALSE, 2),
('qo_syllable_32_c', 'q_syllable_32', 'C', 'third syllable', FALSE, 3),
('qo_syllable_32_d', 'q_syllable_32', 'D', 'other 3', FALSE, 4),
('qo_syllable_33_a', 'q_syllable_33', 'A', 'or-ange', TRUE, 1),
('qo_syllable_33_b', 'q_syllable_33', 'B', 'first syllable', FALSE, 2),
('qo_syllable_33_c', 'q_syllable_33', 'C', 'second syllable', FALSE, 3),
('qo_syllable_33_d', 'q_syllable_33', 'D', 'third syllable', FALSE, 4),
('qo_syllable_34_a', 'q_syllable_34', 'A', 'morn-ing', TRUE, 1),
('qo_syllable_34_b', 'q_syllable_34', 'B', 'first syllable', FALSE, 2),
('qo_syllable_34_c', 'q_syllable_34', 'C', 'second syllable', FALSE, 3),
('qo_syllable_34_d', 'q_syllable_34', 'D', 'third syllable', FALSE, 4),
('qo_syllable_35_a', 'q_syllable_35', 'A', 'les-son', TRUE, 1),
('qo_syllable_35_b', 'q_syllable_35', 'B', 'first syllable', FALSE, 2),
('qo_syllable_35_c', 'q_syllable_35', 'C', 'second syllable', FALSE, 3),
('qo_syllable_35_d', 'q_syllable_35', 'D', 'third syllable', FALSE, 4),
('qo_syllable_36_a', 'q_syllable_36', 'A', 'yel-low', TRUE, 1),
('qo_syllable_36_b', 'q_syllable_36', 'B', 'first syllable', FALSE, 2),
('qo_syllable_36_c', 'q_syllable_36', 'C', 'second syllable', FALSE, 3),
('qo_syllable_36_d', 'q_syllable_36', 'D', 'third syllable', FALSE, 4),
('qo_syllable_37_a', 'q_syllable_37', 'A', 'open syllable', TRUE, 1),
('qo_syllable_37_b', 'q_syllable_37', 'B', 'first syllable', FALSE, 2),
('qo_syllable_37_c', 'q_syllable_37', 'C', 'second syllable', FALSE, 3),
('qo_syllable_37_d', 'q_syllable_37', 'D', 'third syllable', FALSE, 4),
('qo_syllable_38_a', 'q_syllable_38', 'A', 'closed syllable', TRUE, 1),
('qo_syllable_38_b', 'q_syllable_38', 'B', 'first syllable', FALSE, 2),
('qo_syllable_38_c', 'q_syllable_38', 'C', 'second syllable', FALSE, 3),
('qo_syllable_38_d', 'q_syllable_38', 'D', 'third syllable', FALSE, 4),
('qo_syllable_39_a', 'q_syllable_39', 'A', 'open syllable', TRUE, 1),
('qo_syllable_39_b', 'q_syllable_39', 'B', 'first syllable', FALSE, 2),
('qo_syllable_39_c', 'q_syllable_39', 'C', 'second syllable', FALSE, 3),
('qo_syllable_39_d', 'q_syllable_39', 'D', 'third syllable', FALSE, 4),
('qo_syllable_40_a', 'q_syllable_40', 'A', 'closed syllable', TRUE, 1),
('qo_syllable_40_b', 'q_syllable_40', 'B', 'first syllable', FALSE, 2),
('qo_syllable_40_c', 'q_syllable_40', 'C', 'second syllable', FALSE, 3),
('qo_syllable_40_d', 'q_syllable_40', 'D', 'third syllable', FALSE, 4),
('qo_syllable_41_a', 'q_syllable_41', 'A', '-tion forms /ʃn/', TRUE, 1),
('qo_syllable_41_b', 'q_syllable_41', 'B', 'first syllable', FALSE, 2),
('qo_syllable_41_c', 'q_syllable_41', 'C', 'second syllable', FALSE, 3),
('qo_syllable_41_d', 'q_syllable_41', 'D', 'third syllable', FALSE, 4),
('qo_syllable_42_a', 'q_syllable_42', 'A', '-ple ending', TRUE, 1),
('qo_syllable_42_b', 'q_syllable_42', 'B', 'first syllable', FALSE, 2),
('qo_syllable_42_c', 'q_syllable_42', 'C', 'second syllable', FALSE, 3),
('qo_syllable_42_d', 'q_syllable_42', 'D', 'third syllable', FALSE, 4),
('qo_syllable_43_a', 'q_syllable_43', 'A', '-dle ending', TRUE, 1),
('qo_syllable_43_b', 'q_syllable_43', 'B', 'first syllable', FALSE, 2),
('qo_syllable_43_c', 'q_syllable_43', 'C', 'second syllable', FALSE, 3),
('qo_syllable_43_d', 'q_syllable_43', 'D', 'third syllable', FALSE, 4),
('qo_syllable_44_a', 'q_syllable_44', 'A', '-ple ending', TRUE, 1),
('qo_syllable_44_b', 'q_syllable_44', 'B', 'first syllable', FALSE, 2),
('qo_syllable_44_c', 'q_syllable_44', 'C', 'second syllable', FALSE, 3),
('qo_syllable_44_d', 'q_syllable_44', 'D', 'third syllable', FALSE, 4),
('qo_syllable_45_a', 'q_syllable_45', 'A', '2', FALSE, 1),
('qo_syllable_45_b', 'q_syllable_45', 'B', '3', FALSE, 2),
('qo_syllable_45_c', 'q_syllable_45', 'C', '4', TRUE, 3),
('qo_syllable_45_d', 'q_syllable_45', 'D', '5', FALSE, 4),
('qo_syllable_46_a', 'q_syllable_46', 'A', '2', FALSE, 1),
('qo_syllable_46_b', 'q_syllable_46', 'B', '3', FALSE, 2),
('qo_syllable_46_c', 'q_syllable_46', 'C', '4', TRUE, 3),
('qo_syllable_46_d', 'q_syllable_46', 'D', '5', FALSE, 4),
('qo_syllable_47_a', 'q_syllable_47', 'A', 'third syllable', TRUE, 1),
('qo_syllable_47_b', 'q_syllable_47', 'B', 'first syllable', FALSE, 2),
('qo_syllable_47_c', 'q_syllable_47', 'C', 'second syllable', FALSE, 3),
('qo_syllable_47_d', 'q_syllable_47', 'D', 'other 3', FALSE, 4),
('qo_syllable_48_a', 'q_syllable_48', 'A', 'third syllable', TRUE, 1),
('qo_syllable_48_b', 'q_syllable_48', 'B', 'first syllable', FALSE, 2),
('qo_syllable_48_c', 'q_syllable_48', 'C', 'second syllable', FALSE, 3),
('qo_syllable_48_d', 'q_syllable_48', 'D', 'other 3', FALSE, 4);

