ALTER TABLE phonemes ADD COLUMN audio_us_url VARCHAR(500) NULL AFTER audio_url;
ALTER TABLE phonemes ADD COLUMN audio_gb_url VARCHAR(500) NULL AFTER audio_us_url;

UPDATE phonemes SET audio_us_url = audio_url WHERE audio_url IS NOT NULL AND audio_us_url IS NULL;

UPDATE phonemes SET ipa='/iː/', group_code='VOWEL', category='长元音', sort_order=1, detail_json='{"description":"长元音 /iː/，先观察口型，再跟读例词。","mouth":{"type":"smile","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"see","ipa":"/siː/","meaning":"看见","audioUrl":null}],"memoryTip":"用 see 记住 /iː/。","speechFallback":"see"}' WHERE id='p_2';
UPDATE phonemes SET ipa='/ɪ/', group_code='VOWEL', category='短元音', sort_order=2, detail_json='{"description":"短元音 /ɪ/，先观察口型，再跟读例词。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"sit","ipa":"/sɪt/","meaning":"坐","audioUrl":null}],"memoryTip":"用 sit 记住 /ɪ/。","speechFallback":"sit"}' WHERE id='p_1';
UPDATE phonemes SET ipa='/p/', group_code='CONSONANT', category='爆破音', sort_order=1, detail_json='{"description":"爆破音 /p/，注意气流和声带状态。","mouth":{"type":"closed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"pen","ipa":"/pen/","meaning":"钢笔","audioUrl":null}],"memoryTip":"用 pen 记住 /p/。","speechFallback":"pen"}' WHERE id='p_3';

INSERT IGNORE INTO phonemes (id, ipa, group_code, category, audio_url, audio_us_url, audio_gb_url, sort_order, detail_json) VALUES
('p_v_03', '/e/', 'VOWEL', '短元音', NULL, NULL, NULL, 3, '{"description":"短元音 /e/，先观察口型，再跟读例词。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"bed","ipa":"/bed/","meaning":"床","audioUrl":null}],"memoryTip":"用 bed 记住 /e/。","speechFallback":"bed"}'),
('p_v_04', '/æ/', 'VOWEL', '短元音', NULL, NULL, NULL, 4, '{"description":"短元音 /æ/，先观察口型，再跟读例词。","mouth":{"type":"open","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"cat","ipa":"/kæt/","meaning":"猫","audioUrl":null}],"memoryTip":"用 cat 记住 /æ/。","speechFallback":"cat"}'),
('p_v_05', '/ɜː/', 'VOWEL', '长元音', NULL, NULL, NULL, 5, '{"description":"长元音 /ɜː/，先观察口型，再跟读例词。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"bird","ipa":"/bɜːd/","meaning":"鸟","audioUrl":null}],"memoryTip":"用 bird 记住 /ɜː/。","speechFallback":"bird"}'),
('p_v_06', '/ə/', 'VOWEL', '短元音', NULL, NULL, NULL, 6, '{"description":"短元音 /ə/，先观察口型，再跟读例词。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"about","ipa":"/əˈbaʊt/","meaning":"关于","audioUrl":null}],"memoryTip":"用 about 记住 /ə/。","speechFallback":"about"}'),
('p_v_07', '/ʌ/', 'VOWEL', '短元音', NULL, NULL, NULL, 7, '{"description":"短元音 /ʌ/，先观察口型，再跟读例词。","mouth":{"type":"open","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"cup","ipa":"/kʌp/","meaning":"杯子","audioUrl":null}],"memoryTip":"用 cup 记住 /ʌ/。","speechFallback":"cup"}'),
('p_v_08', '/uː/', 'VOWEL', '长元音', NULL, NULL, NULL, 8, '{"description":"长元音 /uː/，先观察口型，再跟读例词。","mouth":{"type":"closed","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"blue","ipa":"/bluː/","meaning":"蓝色","audioUrl":null}],"memoryTip":"用 blue 记住 /uː/。","speechFallback":"blue"}'),
('p_v_09', '/ʊ/', 'VOWEL', '短元音', NULL, NULL, NULL, 9, '{"description":"短元音 /ʊ/，先观察口型，再跟读例词。","mouth":{"type":"closed","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"book","ipa":"/bʊk/","meaning":"书","audioUrl":null}],"memoryTip":"用 book 记住 /ʊ/。","speechFallback":"book"}'),
('p_v_10', '/ɔː/', 'VOWEL', '长元音', NULL, NULL, NULL, 10, '{"description":"长元音 /ɔː/，先观察口型，再跟读例词。","mouth":{"type":"open","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"law","ipa":"/lɔː/","meaning":"法律","audioUrl":null}],"memoryTip":"用 law 记住 /ɔː/。","speechFallback":"law"}'),
('p_v_11', '/ɒ/', 'VOWEL', '短元音', NULL, NULL, NULL, 11, '{"description":"短元音 /ɒ/，先观察口型，再跟读例词。","mouth":{"type":"open","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"hot","ipa":"/hɒt/","meaning":"热的","audioUrl":null}],"memoryTip":"用 hot 记住 /ɒ/。","speechFallback":"hot"}'),
('p_v_12', '/ɑː/', 'VOWEL', '长元音', NULL, NULL, NULL, 12, '{"description":"长元音 /ɑː/，先观察口型，再跟读例词。","mouth":{"type":"open","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"car","ipa":"/kɑː/","meaning":"汽车","audioUrl":null}],"memoryTip":"用 car 记住 /ɑː/。","speechFallback":"car"}'),
('p_v_13', '/eɪ/', 'VOWEL', '双元音', NULL, NULL, NULL, 13, '{"description":"双元音 /eɪ/，先观察口型，再跟读例词。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"day","ipa":"/deɪ/","meaning":"一天","audioUrl":null}],"memoryTip":"用 day 记住 /eɪ/。","speechFallback":"day"}'),
('p_v_14', '/aɪ/', 'VOWEL', '双元音', NULL, NULL, NULL, 14, '{"description":"双元音 /aɪ/，先观察口型，再跟读例词。","mouth":{"type":"open","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"my","ipa":"/maɪ/","meaning":"我的","audioUrl":null}],"memoryTip":"用 my 记住 /aɪ/。","speechFallback":"my"}'),
('p_v_15', '/ɔɪ/', 'VOWEL', '双元音', NULL, NULL, NULL, 15, '{"description":"双元音 /ɔɪ/，先观察口型，再跟读例词。","mouth":{"type":"open","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"boy","ipa":"/bɔɪ/","meaning":"男孩","audioUrl":null}],"memoryTip":"用 boy 记住 /ɔɪ/。","speechFallback":"boy"}'),
('p_v_16', '/əʊ/', 'VOWEL', '双元音', NULL, NULL, NULL, 16, '{"description":"双元音 /əʊ/，先观察口型，再跟读例词。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"go","ipa":"/ɡəʊ/","meaning":"去","audioUrl":null}],"memoryTip":"用 go 记住 /əʊ/。","speechFallback":"go"}'),
('p_v_17', '/aʊ/', 'VOWEL', '双元音', NULL, NULL, NULL, 17, '{"description":"双元音 /aʊ/，先观察口型，再跟读例词。","mouth":{"type":"open","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"now","ipa":"/naʊ/","meaning":"现在","audioUrl":null}],"memoryTip":"用 now 记住 /aʊ/。","speechFallback":"now"}'),
('p_v_18', '/ɪə/', 'VOWEL', '双元音', NULL, NULL, NULL, 18, '{"description":"双元音 /ɪə/，先观察口型，再跟读例词。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"near","ipa":"/nɪə/","meaning":"附近","audioUrl":null}],"memoryTip":"用 near 记住 /ɪə/。","speechFallback":"near"}'),
('p_v_19', '/eə/', 'VOWEL', '双元音', NULL, NULL, NULL, 19, '{"description":"双元音 /eə/，先观察口型，再跟读例词。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"hair","ipa":"/heə/","meaning":"头发","audioUrl":null}],"memoryTip":"用 hair 记住 /eə/。","speechFallback":"hair"}'),
('p_v_20', '/ʊə/', 'VOWEL', '双元音', NULL, NULL, NULL, 20, '{"description":"双元音 /ʊə/，先观察口型，再跟读例词。","mouth":{"type":"closed","color":"#3154ff"},"pronunciationSteps":["观察嘴唇和下颌位置","保持舌位稳定","先慢读，再连到例词"],"exampleWords":[{"wordId":null,"word":"tour","ipa":"/tʊə/","meaning":"旅行","audioUrl":null}],"memoryTip":"用 tour 记住 /ʊə/。","speechFallback":"tour"}'),
('p_c_02', '/b/', 'CONSONANT', '爆破音', NULL, NULL, NULL, 2, '{"description":"爆破音 /b/，注意气流和声带状态。","mouth":{"type":"closed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"bed","ipa":"/bed/","meaning":"床","audioUrl":null}],"memoryTip":"用 bed 记住 /b/。","speechFallback":"bed"}'),
('p_c_03', '/t/', 'CONSONANT', '爆破音', NULL, NULL, NULL, 3, '{"description":"爆破音 /t/，注意气流和声带状态。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"tea","ipa":"/tiː/","meaning":"茶","audioUrl":null}],"memoryTip":"用 tea 记住 /t/。","speechFallback":"tea"}'),
('p_c_04', '/d/', 'CONSONANT', '爆破音', NULL, NULL, NULL, 4, '{"description":"爆破音 /d/，注意气流和声带状态。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"dog","ipa":"/dɒɡ/","meaning":"狗","audioUrl":null}],"memoryTip":"用 dog 记住 /d/。","speechFallback":"dog"}'),
('p_c_05', '/k/', 'CONSONANT', '爆破音', NULL, NULL, NULL, 5, '{"description":"爆破音 /k/，注意气流和声带状态。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"cat","ipa":"/kæt/","meaning":"猫","audioUrl":null}],"memoryTip":"用 cat 记住 /k/。","speechFallback":"cat"}'),
('p_c_06', '/ɡ/', 'CONSONANT', '爆破音', NULL, NULL, NULL, 6, '{"description":"爆破音 /ɡ/，注意气流和声带状态。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"go","ipa":"/ɡəʊ/","meaning":"去","audioUrl":null}],"memoryTip":"用 go 记住 /ɡ/。","speechFallback":"go"}'),
('p_c_07', '/f/', 'CONSONANT', '摩擦音', NULL, NULL, NULL, 7, '{"description":"摩擦音 /f/，注意气流和声带状态。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"fish","ipa":"/fɪʃ/","meaning":"鱼","audioUrl":null}],"memoryTip":"用 fish 记住 /f/。","speechFallback":"fish"}'),
('p_c_08', '/v/', 'CONSONANT', '摩擦音', NULL, NULL, NULL, 8, '{"description":"摩擦音 /v/，注意气流和声带状态。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"van","ipa":"/væn/","meaning":"货车","audioUrl":null}],"memoryTip":"用 van 记住 /v/。","speechFallback":"van"}'),
('p_c_09', '/θ/', 'CONSONANT', '摩擦音', NULL, NULL, NULL, 9, '{"description":"摩擦音 /θ/，注意气流和声带状态。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"think","ipa":"/θɪŋk/","meaning":"思考","audioUrl":null}],"memoryTip":"用 think 记住 /θ/。","speechFallback":"think"}'),
('p_c_10', '/ð/', 'CONSONANT', '摩擦音', NULL, NULL, NULL, 10, '{"description":"摩擦音 /ð/，注意气流和声带状态。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"this","ipa":"/ðɪs/","meaning":"这个","audioUrl":null}],"memoryTip":"用 this 记住 /ð/。","speechFallback":"this"}'),
('p_c_11', '/s/', 'CONSONANT', '摩擦音', NULL, NULL, NULL, 11, '{"description":"摩擦音 /s/，注意气流和声带状态。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"sun","ipa":"/sʌn/","meaning":"太阳","audioUrl":null}],"memoryTip":"用 sun 记住 /s/。","speechFallback":"sun"}'),
('p_c_12', '/z/', 'CONSONANT', '摩擦音', NULL, NULL, NULL, 12, '{"description":"摩擦音 /z/，注意气流和声带状态。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"zoo","ipa":"/zuː/","meaning":"动物园","audioUrl":null}],"memoryTip":"用 zoo 记住 /z/。","speechFallback":"zoo"}'),
('p_c_13', '/ʃ/', 'CONSONANT', '摩擦音', NULL, NULL, NULL, 13, '{"description":"摩擦音 /ʃ/，注意气流和声带状态。","mouth":{"type":"closed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"ship","ipa":"/ʃɪp/","meaning":"船","audioUrl":null}],"memoryTip":"用 ship 记住 /ʃ/。","speechFallback":"ship"}'),
('p_c_14', '/ʒ/', 'CONSONANT', '摩擦音', NULL, NULL, NULL, 14, '{"description":"摩擦音 /ʒ/，注意气流和声带状态。","mouth":{"type":"closed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"vision","ipa":"/ˈvɪʒən/","meaning":"视力","audioUrl":null}],"memoryTip":"用 vision 记住 /ʒ/。","speechFallback":"vision"}'),
('p_c_15', '/h/', 'CONSONANT', '摩擦音', NULL, NULL, NULL, 15, '{"description":"摩擦音 /h/，注意气流和声带状态。","mouth":{"type":"open","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"hat","ipa":"/hæt/","meaning":"帽子","audioUrl":null}],"memoryTip":"用 hat 记住 /h/。","speechFallback":"hat"}'),
('p_c_16', '/tʃ/', 'CONSONANT', '破擦音', NULL, NULL, NULL, 16, '{"description":"破擦音 /tʃ/，注意气流和声带状态。","mouth":{"type":"closed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"chair","ipa":"/tʃeə/","meaning":"椅子","audioUrl":null}],"memoryTip":"用 chair 记住 /tʃ/。","speechFallback":"chair"}'),
('p_c_17', '/dʒ/', 'CONSONANT', '破擦音', NULL, NULL, NULL, 17, '{"description":"破擦音 /dʒ/，注意气流和声带状态。","mouth":{"type":"closed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"jump","ipa":"/dʒʌmp/","meaning":"跳","audioUrl":null}],"memoryTip":"用 jump 记住 /dʒ/。","speechFallback":"jump"}'),
('p_c_18', '/m/', 'CONSONANT', '鼻音', NULL, NULL, NULL, 18, '{"description":"鼻音 /m/，注意气流和声带状态。","mouth":{"type":"closed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"man","ipa":"/mæn/","meaning":"男人","audioUrl":null}],"memoryTip":"用 man 记住 /m/。","speechFallback":"man"}'),
('p_c_19', '/n/', 'CONSONANT', '鼻音', NULL, NULL, NULL, 19, '{"description":"鼻音 /n/，注意气流和声带状态。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"no","ipa":"/nəʊ/","meaning":"不","audioUrl":null}],"memoryTip":"用 no 记住 /n/。","speechFallback":"no"}'),
('p_c_20', '/ŋ/', 'CONSONANT', '鼻音', NULL, NULL, NULL, 20, '{"description":"鼻音 /ŋ/，注意气流和声带状态。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"sing","ipa":"/sɪŋ/","meaning":"唱歌","audioUrl":null}],"memoryTip":"用 sing 记住 /ŋ/。","speechFallback":"sing"}'),
('p_c_21', '/l/', 'CONSONANT', '舌侧音', NULL, NULL, NULL, 21, '{"description":"舌侧音 /l/，注意气流和声带状态。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"leg","ipa":"/leɡ/","meaning":"腿","audioUrl":null}],"memoryTip":"用 leg 记住 /l/。","speechFallback":"leg"}'),
('p_c_22', '/r/', 'CONSONANT', '近音', NULL, NULL, NULL, 22, '{"description":"近音 /r/，注意气流和声带状态。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"red","ipa":"/red/","meaning":"红色","audioUrl":null}],"memoryTip":"用 red 记住 /r/。","speechFallback":"red"}'),
('p_c_23', '/j/', 'CONSONANT', '近音', NULL, NULL, NULL, 23, '{"description":"近音 /j/，注意气流和声带状态。","mouth":{"type":"smile","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"yes","ipa":"/jes/","meaning":"是","audioUrl":null}],"memoryTip":"用 yes 记住 /j/。","speechFallback":"yes"}'),
('p_c_24', '/w/', 'CONSONANT', '近音', NULL, NULL, NULL, 24, '{"description":"近音 /w/，注意气流和声带状态。","mouth":{"type":"closed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"we","ipa":"/wiː/","meaning":"我们","audioUrl":null}],"memoryTip":"用 we 记住 /w/。","speechFallback":"we"}'),
('p_c_25', '/tr/', 'CONSONANT', '破擦音', NULL, NULL, NULL, 25, '{"description":"破擦音 /tr/，注意气流和声带状态。","mouth":{"type":"closed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"tree","ipa":"/triː/","meaning":"树","audioUrl":null}],"memoryTip":"用 tree 记住 /tr/。","speechFallback":"tree"}'),
('p_c_26', '/dr/', 'CONSONANT', '破擦音', NULL, NULL, NULL, 26, '{"description":"破擦音 /dr/，注意气流和声带状态。","mouth":{"type":"closed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"dress","ipa":"/dres/","meaning":"连衣裙","audioUrl":null}],"memoryTip":"用 dress 记住 /dr/。","speechFallback":"dress"}'),
('p_c_27', '/ts/', 'CONSONANT', '破擦音', NULL, NULL, NULL, 27, '{"description":"破擦音 /ts/，注意气流和声带状态。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"cats","ipa":"/kæts/","meaning":"猫（复数）","audioUrl":null}],"memoryTip":"用 cats 记住 /ts/。","speechFallback":"cats"}'),
('p_c_28', '/dz/', 'CONSONANT', '破擦音', NULL, NULL, NULL, 28, '{"description":"破擦音 /dz/，注意气流和声带状态。","mouth":{"type":"relaxed","color":"#3154ff"},"pronunciationSteps":["摆好舌位和唇形","感受气流与声带状态","连到例词中练习"],"exampleWords":[{"wordId":null,"word":"beds","ipa":"/bedz/","meaning":"床（复数）","audioUrl":null}],"memoryTip":"用 beds 记住 /dz/。","speechFallback":"beds"}');

INSERT INTO content_entries (id, kind, source_id, scope_id, label)
SELECT CONCAT('content_', p.id), 'PHONEME', p.id, '', p.ipa
FROM phonemes p
WHERE NOT EXISTS (
  SELECT 1 FROM content_entries e
  WHERE e.kind = 'PHONEME' AND e.source_id = p.id AND e.scope_id = ''
);

